### ISSUE TITLE
Launching a VANILLA Minecraft Jar

### ISSUE THREAD

**Issue by HorizonCode** [Litarvan/OpenLauncherLib#10]
I Try to run a normal vanilla 1.8 Version but there is no GameType.Vanilla :/

My Code:
http://horizonco.de/paste/?p=Bz1j2

`[06:55:16 ERROR]: Unable to launch
java.lang.ClassCastException: net.minecraft.client.main.Main cannot be cast to net.minecraft.launchwrapper.ITweaker
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98) [bin/:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [bin/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_131]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_131]
	at fr.theshark34.openlauncherlib.internal.InternalLauncher.launch(InternalLauncher.java:166) [openlauncherlib-3.0.3-BETA.jar:?]
	at net.cube.Launcher.start(Launcher.java:33) [bin/:?]
	at net.cube.CubeController$8.run(CubeController.java:763) [bin/:?]`

**Comment by HorizonCode** [comment]
ok now iam getting this error:
`fr.theshark34.openlauncherlib.internal.UnknownMainClassException: net.minecraft.launchwrapper.Launch
	at fr.theshark34.openlauncherlib.internal.InternalLauncher.launch(InternalLauncher.java:114)
	at net.cube.Launcher.start(Launcher.java:44)
	at net.cube.CubeController$8.run(CubeController.java:763)
Caused by: java.lang.ClassNotFoundException: net.minecraft.launchwrapper.Launch
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at fr.theshark34.openlauncherlib.internal.InternalLauncher.launch(InternalLauncher.java:107)
	... 2 more`

**Comment by Jeerrryyyy** [comment]
Hey Horizon. Maybe you can awnser here how you fixed it? I'am struggling with the same problem at the time. Would be nice if you can help.

**Comment by HorizonCode** [comment]
just set the GameTweak to null

**Comment by tikaros** [comment]
https://hatebin.com/fjcbtimdjq
