### ISSUE TITLE
Invoked method returned an exception

### ISSUE THREAD

**Issue by XenoPyax** [Litarvan/OpenLauncherLib#13]
Getting this when trying to launch example code...
`Exception in thread "main" fr.theshark34.openlauncherlib.LaunchException: Invoked method returned an exception
	at fr.theshark34.openlauncherlib.internal.InternalLauncher.launch(InternalLauncher.java:183)
	at Main.main(Main.java:39)
Caused by: java.lang.SecurityException: class "bhz"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(Unknown Source)
	at java.lang.ClassLoader.preDefineClass(Unknown Source)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraft.client.main.Main.main(SourceFile:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at fr.theshark34.openlauncherlib.internal.InternalLauncher.launch(InternalLauncher.java:173)
	... 1 more
`

**Comment by Litarvan** [comment]
Minecraft crashed, in this case the crash is caused by a modification of the minecraft.jar along with Forge, which does not allow such edits.
