### ISSUE TITLE
Problème de token

### ISSUE THREAD

**Issue by Tk77185** [Litarvan/OpenLauncherLib#14]
Bonjour quand je lance le launcher, je me login et le launcher fait ses màj et au moment de lancer le jeu, il ne lance pas et fait ceci : [OpenLauncherLib] Lancement de net.minecraft.client.main.Main
joptsimple.MissingRequiredOptionException: Missing required option(s) ['accessToken']
Exception in thread "main" at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:375)
at joptsimple.OptionParser.parse(OptionParser.java:365)
at net.minecraft.client.main.Main.main(SourceFile:51)

https://pastebin.com/SkvtEzaS

Une solution ? merci

**Comment by Litarvan** [comment]
Dupliqué, évite de créer deux fois la même issue
