### ISSUE TITLE
Argument java

### ISSUE THREAD

**Issue by Kakumi** [Litarvan/OpenLauncherLib#15]
Bonsoir,

J'ai voulu modifier la ram en faisant profile.setVmArgs mais le jeu crash directement avec l'erreur :
`java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_171]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.UnsatisfiedLinkError: no lwjgl in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_171]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_171]
	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_171]
	at org.lwjgl.Sys$1.run(Sys.java:73) ~[lwjgl-2.9.1.jar:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_171]
	at org.lwjgl.Sys.doLoadLibrary(Sys.java:66) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.Sys.loadLibrary(Sys.java:95) ~[lwjgl-2.9.1.jar:?]
	at org.lwjgl.Sys.<clinit>(Sys.java:112) ~[lwjgl-2.9.1.jar:?]
	at net.minecraft.client.Minecraft.func_71386_F(Minecraft.java:2671) ~[bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:72) ~[Main.class:?]
	... 6 more`
J'ai aussi essayer la version 3.0.3 & 3.0.2 mais toujours ce problème...

**Comment by Litarvan** [comment]
Je sais pas si tu as réglé ça depuis, mais il manquait les natives dans tes fichiers
