### ISSUE TITLE
Openlauncherlib 3.0.4 & Java 9

### ISSUE THREAD

**Issue by Bencor29** [Litarvan/OpenLauncherLib#24]
Bonjour,

Je me rend compte que malgré la description de la version 3.0.4, cette dernière n'est pas compatible avec Java 9 (compilé avec JDK-9).

~~~
[OpenLauncherLib] Lancement de net.minecraft.launchwrapper.Launch 
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
Exception in thread "main" java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
~~~

Une fois compilé avec Maven en source 1.6, là tout se passe bien.

Ma question est alors la suivante:
OpenlauncherLib 3.0.4 est-il compatible avec le compilateur du JDK-9 ?

Merci bien.

Bonne journée,
Bencor29

**Comment by Litarvan** [comment]
Malheureusement les versions anciennes de Forge ne sont pas compatibles avec Java >=9
