### ISSUE TITLE
Créer son launcher en 1.15.2

### ISSUE THREAD

**Issue by chouuul** [Litarvan/OpenLauncherLib#25]
Bonjour, j'aimerai savoir si cette bibliothèque est disponible et fonctionnel pour un launcher en 1.15.2 !

J'ai fais quelques test de mon côté mais la méthode suivante change de comportement entre la version 1.12.2 et 1.15.2 (Mises à jours faites et objets mis à jour avec les nouvelles fonctionnalités d'openlauncherlib 3.0.5 :

	public static void Launch() throws LaunchException{
		
		ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(UI_INFOS, GameFolder.BASIC, authInfos);
		profile.getVmArgs().addAll(Arrays.asList(LauncherFrame.getInstance().getLauncherPanel().getRamSelector().getRamArguments()));
		ExternalLauncher launcher = new ExternalLauncher(profile);
		
		Process p = launcher.launch();	
	
		
		
		ProcessLogManager manager = new ProcessLogManager(p.getInputStream(), new File(UI_DIR, "logs.txt"));
		manager.start();
		
		
		try {
			Thread.sleep(2500L);
			LauncherFrame.getInstance().setVisible(false);
			p.waitFor();
		}
		catch (InterruptedException e){
			e.printStackTrace();
		}
		System.exit(0);
	}
	

Dans la console :

[OpenLauncherLib] Creation d'un profil de lancement externe pour Minecraft 1.15.2 
[OpenLauncherLib] Verification du dossier de Minecraft C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3 
[OpenLauncherLib] Generation du classpath 
[OpenLauncherLib] Termine 
[OpenLauncherLib] OpenLauncherLib 3.0.4 par Adrien 'Litarvan' Navratil - Systeme de lancement externe 
[OpenLauncherLib] Commande entiere : "C:\Program Files\Java\jre1.8.0_241\bin\java" -XX:-UseAdaptiveSizePolicy -XX:+UseConcMarkSweepGC -Djava.library.path=C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\natives -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -Xms8704M -Xmx9216M -cp C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\accesstransformers-2.0.0-milestone.1-shadowed.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\animal-sniffer-annotations-1.14.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-6.1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-7.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-analysis-6.1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-commons-6.1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-commons-7.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-tree-6.1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\asm-tree-7.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\authlib-1.5.25.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\binarypatcher-1.0.12.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\brigadier-1.0.17.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\checker-qual-2.0.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\client-1.15.2-20200122.131323-srg.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\client-1.15.2-extra.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\client-1.15.2-slim.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\commons-codec-1.10.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\commons-compress-1.8.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\commons-io-2.4.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\commons-io-2.5.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\commons-lang3-3.5.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\commons-logging-1.1.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\core-3.6.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\coremods-2.0.0-milestone.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\datafixerupper-2.0.24.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\error_prone_annotations-2.1.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\eventbus-2.0.0-milestone.1-service.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\fastutil-8.2.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\forge-1.15.2-31.1.14-client.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\forge-1.15.2-31.1.14-universal.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\forge-1.15.2-31.1.14.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\forgespi-2.0.0-milestone.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\grossjava9hacks-1.1.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\gson-2.8.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\guava-20.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\guava-21.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\guava-25.1-jre.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\httpclient-4.3.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\httpcore-4.3.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\icu4j-core-mojang-51.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\installertools-1.1.4.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\j2objc-annotations-1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jarsplitter-1.1.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\javabridge-1.0.22.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\javaxdelta-2.0.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jinput-2.0.5.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jline-3.12.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jna-4.4.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jopt-simple-4.9.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jopt-simple-5.0.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jopt-simple-5.0.4.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jsr305-3.0.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\jutils-1.0.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\log4j-api-2.11.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\log4j-api-2.8.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\log4j-core-2.11.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\log4j-core-2.8.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-glfw-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-glfw-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-jemalloc-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-jemalloc-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-openal-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-openal-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-opengl-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-opengl-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-stb-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-stb-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-tinyfd-3.2.2-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lwjgl-tinyfd-3.2.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\lzma-java-1.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\maven-artifact-3.6.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\modlauncher-5.0.0-milestone.4.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\netty-all-4.1.25.Final.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\opencsv-2.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\oshi-core-1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\patchy-1.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\platform-3.4.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\SpecialSource-1.8.5.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\terminalconsoleappender-1.2.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\text2speech-1.11.3-natives-windows.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\text2speech-1.11.3.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\toml-3.6.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\trove-1.0.2.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\typetools-0.6.1.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\libs\unsafe-0.2.0.jar;C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\minecraft.jar net.minecraft.launchwrapper.Launch --username=ShiroLuna1920 --accessToken { DONNEES PERSONNELLES} --version 1.15.2 --gameDir C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3 --assetsDir C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\assets --assetIndex 1.13.1 --userProperties {} --uuid 4d4f770bf62d40bb96e76423290f0ee5 --userType legacy --launchTarget fmlclient --fml.forgeVersion 25.0.219 --fml.mcVersion 1.13.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20190213.203750 --tweakClass cpw.mods.fml.common.launcher.FMLTweaker  
[OpenLauncherLib] Lancement de net.minecraft.launchwrapper.Launch 
Erreur : impossible de trouver ou charger la classe principale net.minecraft.launchwrapper.Launch

Ai-je un problème de libs ? de natives ( Elles sont horribles à trouver xD ) ? Ou tout simplement ce n'est pas encore possible ?

**Comment by Litarvan** [comment]
Salut ! Il faut selectionner **V1_13_HIGHER_FORGE** en GameType, et ne. pas mettre de GameTweak, retente avec ça

**Comment by chouuul** [comment]
Merci d'avoir répondu rapidement ! Cela fait plaisir à voir :D

J'ai donc remplacé les GameTweak par null
et voici le résultat :

[18:46:20] [main/WARN]: Configuration file C:\Users\vanil\AppData\Roaming\.UltimateIndustriesBETAV3\config\fml.toml is not correct. Correcting
[18:46:20] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[18:46:20] [main/WARN]: Incorrect key [defaultConfigPath] was corrected from null to defaultconfigs
[18:46:20] [main/FATAL]: Failed to find forge version 25.0.219 for MC 1.13.2 at C:\Users\net\minecraftforge\forge\1.13.2-25.0.219\forge-1.13.2-25.0.219-universal.jar
Exception in thread "main" [18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: Missing forge!
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLCommonLaunchHandler.validatePaths(FMLCommonLaunchHandler.java:118)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLLoader.setupLaunchHandler(FMLLoader.java:195)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.loading.FMLServiceProvider.initialize(FMLServiceProvider.java:92)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServiceDecorator.onInitialize(TransformationServiceDecorator.java:68)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.lambda$initialiseTransformationServices$7(TransformationServicesHandler.java:107)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.util.HashMap$Values.forEach(Unknown Source)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initialiseTransformationServices(TransformationServicesHandler.java:107)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:59)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:75)
[18:46:20] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)

**Comment by chaun14** [comment]
J'ai ce bug aussi, il vient de la librairie. Le plus marrant est que le mauvais chemin est spécifié nulle part dans les arguments de lancement. Pour lancer forge 1.13 ou plus je pense que le plus simple serait de changer de librairie

**Comment by ElBrigos** [comment]
c'est à dire ? ou on peut trouver les librairies en question ?

**Comment by Litarvan** [comment]
Le support Forge récent est un peu bancal, je vais intégrer ça proprement sous peu
