### ISSUE TITLE
LogUtil can't initialize

### ISSUE THREAD

**Issue by SemBi0s** [Litarvan/OpenLauncherLib#28]
Lorsque je créer un AuthInfos , j'obtiens l'erreur suivante : 

`Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: Could not initialize class fr.theshark34.openlauncherlib.util.LogUtil
	at fr.theshark34.openlauncherlib.minecraft.MinecraftLauncher.createInternalProfile(MinecraftLauncher.java:63)
	at fr.elnathoune.timelia.launcher.Launcher.<init>(Launcher.java:30)
	at fr.elnathoune.timelia.launcher.LauncherPanel.onEvent(LauncherPanel.java:97)
	at fr.theshark34.swinger.abstractcomponents.AbstractButton.mouseReleased(AbstractButton.java:81)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4548)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
` 
Je ne peut donc pas lancer le jeu par la suite.

**Comment by SemBi0s** [comment]
Non pas _AuthInfos_, mais **GameInfos**

**Comment by Litarvan** [comment]
Salut ! Tu n'aurais pas une suite à l'erreur ?

**Comment by SemBi0s** [comment]
Non, je n'ai pas d'autres erreurs que celle-ci,  elle m'empêche de créer le profil pour lancer le jeu

**Comment by SemBi0s** [comment]
J'ai comme l'impression que je ne peux pas appeler la class de manière static,  j'ai le même résultat avec une class de test que j'ai créée

**Comment by Litarvan** [comment]
Tu utilises quelle version de Java ? Et tu es sur quel OS ?

**Comment by SemBi0s** [comment]
Java JDK 14 sous windows

**Comment by Litarvan** [comment]
Tu as toujours ce problème ?
