### ISSUE TITLE
Exception in thread main

### ISSUE THREAD

**Issue by ItsBursty** [Litarvan/OpenLauncherLib#32]
Bonsoir,
J'ai créer un launcher minecraft en suivant la série de Litarvan mais quand j'ai voulu appuyer sur "jouer" sur le launcher, la console me met que le jeu s'est exécuté avec succès sauf que rien n'apparait sauf cette erreur dans la console :/  : 
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Je ne sais pas quoi faire j'ai enlevé les fichiers dans le serveur puis je les ai remis, essayé de voir si tout les fichiers dans libs et dans natives étaient bien présentes et non toujours rien...
Le jeu était censé se lancer en 1.12.2 forge.
Merci d'avance à ceux qui veulent bien m'aider
Bonne soirée

**Comment by Litarvan** [comment]
Les anciennes versions de Forge ne sont malheureusement pas compatibles avec Java 9, on y peut pas grand chose à ma connaissance :/
