### ISSUE TITLE
Java SecurityException au lancement [FR]

### ISSUE THREAD

**Issue by Xen0Xys** [Litarvan/OpenLauncherLib#33]
Bonjour, j'utilise le code suivant et j'obtient l'erreur suivante:

La ligne Gradle de la librairie:
```gradle
compile group: 'fr.flowarg', name: 'openlauncherlib', version: '3.1.5'
```

Mon code:
```java
GameInfos infos = new GameInfos("NetherRP", new GameVersion("1.16.5", GameType.V1_13_HIGHER_VANILLA), new GameTweak[] {});
AuthInfos authInfos = new AuthInfos("Xen0Xys", "", "");
ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(infos, GameFolder.BASIC, authInfos);
ExternalLauncher launcher = new ExternalLauncher(profile);
launcher.launch();
```

Les logs (j'ai retiré la ligne de la commande entière):
```
[OpenLauncherLib] Creation d'un profil de lancement externe pour Minecraft .1.16.5
[OpenLauncherLib] Verification du dossier de Minecraft .C:\Users\red57\AppData\Roaming\.NetherRP
[OpenLauncherLib] Generation du classpath
[OpenLauncherLib] Termine
[OpenLauncherLib] OpenLauncherLib 3.1.5-FLOWARGVERSION par Adrien 'Litarvan' Navratil et FlowArg (Flow Arg) - Systeme de lancement externe
(ligne de la commande entière)
[OpenLauncherLib] Lancement de .net.minecraft.client.main.Main
Exception in thread "main" java.lang.SecurityException: class "x"'s signer information does not match signer information of other classes in the same package
	at java.lang.ClassLoader.checkCerts(ClassLoader.java:891)
	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:661)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:754)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:468)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:64)
```

**Comment by Litarvan** [comment]
Hello, ça vient du fait que tu aies modifié le minecraft.jar mais en laissant META-INF dedans je pense, en tout cas ce n'est malheureusement pas un problème de la librairie mais bien un de ton jeu

**Comment by Xen0Xys** [comment]
Bonjour,
Je n'ai toujours pas réussi à résoudre le problème:
  - En laissant le META-INF j'ai toujours la même erreur
  - En le supprimant du client.jar (1.17.1.jar venant du dossier version renommé) j'ai une nouvelle erreur:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: class pg can not implement ou, because it is not an interface (ou is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:855)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:753)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:676)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:634)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:182)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at dh.<clinit>(SourceFile:24)
	at ab.<clinit>(SourceFile:197)
	at net.minecraft.client.main.Main.main(SourceFile:47)
```

Mon code actuel:
```
Path path = new File("C:\\Users\\username\\AppData\\Roaming\\.servername").toPath();

GameInfos infos = new GameInfos("servername", path, new GameVersion("1.17.1", GameType.V1_13_HIGHER_VANILLA), new GameTweak[]{});
AuthInfos authInfos = new AuthInfos("Xen0Xys", "", "");


try {
    MinecraftLauncher.checkFolder(GameFolder.FLOW_UPDATER, path);
    ExternalLaunchProfile profile = MinecraftLauncher.createExternalProfile(infos, GameFolder.FLOW_UPDATER, authInfos);
    ExternalLauncher launcher = new ExternalLauncher(profile);

    launcher.launch();
} catch (LaunchException e) {
    e.printStackTrace();
}
```

J'utilise la version 3.2.2 de OpenLauncherLib

Je vous remercie d'avance pour votre aide, j'espère que vous saurez m'aider!
